apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/component: cluster
  annotations:
    strimzi.io/node-pools: enabled
spec:
  kafka:
    version: 4.0.0
    # Listeners for client connections
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    # Kafka broker configuration
    config:
      # Replication settings for production reliability
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2

      # Protocol version
      inter.broker.protocol.version: "4.0"

      # Log retention (7 days)
      log.retention.hours: 168
      log.segment.bytes: 1073741824

      # Compression
      compression.type: producer

      # Auto create topics (disable in production)
      auto.create.topics.enable: true

    # JMX monitoring
    jmxOptions: {}

    # Prometheus metrics export
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml

  # Entity Operator for managing topics and users
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 256Mi
          cpu: 100m
        limits:
          memory: 512Mi
          cpu: 500m
    userOperator:
      resources:
        requests:
          memory: 256Mi
          cpu: 100m
        limits:
          memory: 512Mi
          cpu: 500m
