---
# CVE Reporter Deployment Playbook
# Deploys CVE email reporter to Harbor namespace
# Usage: SMTP_PASSWORD=yourpass ansible-playbook cve-reporter-deploy.yml

- name: Deploy CVE Email Reporter
  hosts: localhost
  connection: local
  vars:
    smtp_host: smtp-mail.outlook.com
    smtp_port: 587
    smtp_username: "damoke012@hotmail.com"
    smtp_password: "{{ lookup('env', 'SMTP_PASSWORD') }}"
    email_from: "harbor-security@lab.ocp.lan"
    email_to: "damoke012@hotmail.com"

  tasks:
    - name: Check SMTP password
      fail:
        msg: "SMTP_PASSWORD environment variable not set"
      when: smtp_password == ""

    - name: Create SMTP secret
      shell: |
        kubectl create secret generic smtp-secret \
          --from-literal=password='{{ smtp_password }}' \
          -n harbor \
          --dry-run=client -o yaml | kubectl apply -f -
      no_log: true

    - name: Create Harbor admin secret
      shell: |
        kubectl create secret generic harbor-admin-secret \
          --from-literal=password='Harbor12345' \
          -n harbor \
          --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy CVE reporter via Helm
      shell: |
        helm upgrade --install cve-reporter \
          /root/platform-gitops/helm-charts/cve-reporter \
          --namespace harbor \
          --set email.smtp.host={{ smtp_host }} \
          --set email.smtp.port={{ smtp_port }} \
          --set email.smtp.username={{ smtp_username }} \
          --set email.from={{ email_from }} \
          --set "email.to[0]={{ email_to }}" \
          --wait --timeout=3m
      register: helm_result

    - name: Wait for deployment
      shell: kubectl rollout status deployment/cve-reporter -n harbor --timeout=2m
      register: rollout_result

    - name: Display next steps
      debug:
        msg:
          - "CVE Reporter deployed successfully!"
          - "Next: Configure Harbor webhook at http://cve-reporter:8080"
