apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cve-reporter.fullname" . }}-scripts
  labels:
    {{- include "cve-reporter.labels" . | nindent 4 }}
data:
  webhook_receiver.py: |
{{ .Files.Get "config/webhook_receiver.py" | indent 4 }}
  weekly_report.py: |
{{ .Files.Get "config/weekly_report.py" | indent 4 }}
