{{- if .Values.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "cve-reporter.fullname" . }}-weekly
  labels:
    {{- include "cve-reporter.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          initContainers:
          - name: install-deps
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            command: ["sh", "-c", "pip install --target=/deps requests urllib3"]
            volumeMounts:
            - name: deps
              mountPath: /deps
          containers:
          - name: weekly-report
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command: ["sh", "-c"]
            args:
            - |
              export PYTHONPATH=/deps:$PYTHONPATH
              python3 /scripts/weekly_report.py
            env:
            - name: HARBOR_URL
              value: {{ .Values.harbor.url | quote }}
            - name: HARBOR_USER
              value: {{ .Values.harbor.username | quote }}
            - name: HARBOR_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.harbor.secretName }}
                  key: password
            - name: SMTP_HOST
              value: {{ .Values.email.smtp.host | quote }}
            - name: SMTP_PORT
              value: {{ .Values.email.smtp.port | quote }}
            - name: SMTP_USER
              value: {{ .Values.email.smtp.username | quote }}
            - name: SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.email.smtp.secretName }}
                  key: password
            - name: EMAIL_FROM
              value: {{ .Values.email.from | quote }}
            - name: EMAIL_TO
              value: {{ join "," .Values.email.to | quote }}
            volumeMounts:
            - name: scripts
              mountPath: /scripts
            - name: deps
              mountPath: /deps
          volumes:
          - name: scripts
            configMap:
              name: {{ include "cve-reporter.fullname" . }}-scripts
              defaultMode: 0755
          - name: deps
            emptyDir: {}
{{- end }}
