apiVersion: v1
kind: Service
metadata:
  name: smtp-relay
  namespace: harbor
  labels:
    app: smtp-relay
spec:
  selector:
    app: smtp-relay
  ports:
  - port: 587
    targetPort: 587
    protocol: TCP
    name: smtp
  type: ClusterIP
